name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: automated-api

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{REPO_NAME}}.

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{REPO_NAME}}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v${{ env.TAG }}
          release_name: "Release $${{REPO_NAME}}"
          body: |
            Docker image is available in the GitHub Container Registry.

            To pull the image:
            ```bash
            docker pull ghcr.io/${{REPO_NAME}}
            ```

            To run the image:
            ```bash
            docker run -p <your-port>:8080 ghcr.io/${{REPO_NAME}}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
